export default {
  PRODUCTS_GET_ALL: "PRODUCTS_GET_ALL",
  PRODUCTS_SET_ALL: "PRODUCTS_SET_ALL",
  PRODUCTS_FILTER: "PRODUCTS_FILTER",
  PRODUCTS_SORT: "PRODUCTS_SORT",
  CATEGORIES_SET_ALL: "CATEGORIES_SET_ALL",
  CATEGORIES_GET_ALL: "CATEGORIES_GET_ALL",
  CART_ADD: "CART_ADD"
}