export default {
  PRODUCTS_GET_ALL: "PRODUCTS_GET_ALL",
  PRODUCTS_SET_ALL: "PRODUCTS_SET_ALL",
  PRODUCTS_FILTER: "PRODUCTS_FILTER",
  CATEGORIES_SET_ALL: "CATEGORIES_SET_ALL",
  CATEGORIES_GET_ALL: "CATEGORIES_GET_ALL"
}